using knkwebapi_v2.Properties;
using knkwebapi_v2.Services.Interfaces;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace knkwebapi_v2.Models;

/// <summary>
/// An additive, create-only seed of the Knights and Kings v1 item catalog, ported from
/// <c>docs/specs/items/V1_SEED_DATA.md</c>. v1's own item table (<c>Products</c>) no longer exists,
/// so the rows below were recovered from v1 players' inventories and ender chests (Old_KnK
/// playerdata) and generated by <c>knk-workspace/scripts/v1-item-port/v1_items.py generate</c> -
/// regenerate rather than hand-edit the <see cref="Blueprints"/> table.
/// <para>
/// Same convention as <see cref="KitSeed"/>: every row is looked up by its natural key
/// (<c>Name</c>, <c>Stars</c> for <see cref="Grade"/>, <c>Key</c> for
/// <see cref="EnchantmentDefinition"/>, <c>NamespaceKey</c> for the Minecraft refs) and reused if
/// it already exists - never updated, diffed or upserted. Join rows (default enchantments, the
/// <see cref="LegacyTag"/> tag) are only added under a blueprint this run itself created, so an
/// existing "Iron Sword"/"Arrow" (KitSeed's) is left exactly as it is.
/// </para>
/// <para>
/// Enchantment keys are either <c>minecraft:*</c> (vanilla; v1's numeric ids mapped to modern
/// keys, created on demand with a catalog-backed <see cref="MinecraftEnchantmentRef"/>) or one of
/// knk-plugin's 12 custom enchantment ids (v1 lore lines such as "§7blindness III"), which
/// <see cref="AbilityDefinition.SeedCanonicalAsync"/> owns - a custom key it hasn't created is
/// logged and skipped, never invented here. Levels are v1's, including vanilla levels above the
/// vanilla cap (the plugin applies vanilla enchantments unsafely).
/// </para>
/// </summary>
public static class ItemBlueprintV1Seed
{
    public const string LegacyTag = "Legacy v1";

    // Fallback MinecraftMaterialRef.Category when the static catalog doesn't know the key.
    private const string FallbackMaterialCategory = "ITEM";

    private static readonly (string Name, string IconKey)[] Categories =
    {
        ("Weapons", "minecraft:iron_sword"),
        ("Armor", "minecraft:iron_chestplate"),
        ("Food", "minecraft:bread"),
        ("Tools", "minecraft:diamond_pickaxe"),
        ("Resources", "minecraft:oak_log"),
        ("Trinkets", "minecraft:diamond"),
    };

    // v1's grade was a bare 1-5 star int; the names for 3-5 are new (only 1/2 exist from KitSeed).
    private static readonly (string Name, int Stars)[] Grades =
    {
        ("Common", 1),
        ("Uncommon", 2),
        ("Rare", 3),
        ("Epic", 4),
        ("Legendary", 5),
    };

    private static readonly (string Key, int Level)[] NoEnchantments = Array.Empty<(string, int)>();

    private sealed record BlueprintSpec(
        string Name,
        string IconKey,
        string DisplayName,
        string Category,
        int? Stars,
        int MaxStackSize,
        (string Key, int Level)[] Enchantments);

    private static readonly BlueprintSpec[] Blueprints =
    {
        new("Raw Fish", "minecraft:cod", "&fRaw Fish", "Food", 2, 64, NoEnchantments),
        new("Golemheart Sword", "minecraft:diamond_sword", "&aGolemheart Sword", "Weapons", 5, 1, NoEnchantments),
        new("Wheat", "minecraft:wheat", "&fWheat", "Resources", 1, 64, NoEnchantments),
        new("Steel Sword", "minecraft:iron_sword", "&9Steel Sword", "Weapons", 3, 1, NoEnchantments),
        new("Spruce Wood", "minecraft:spruce_log", "&fSpruce Wood", "Resources", 1, 64, NoEnchantments),
        new("Iron Sword", "minecraft:iron_sword", "&fIron Sword", "Weapons", null, 1, NoEnchantments),
        new("Cooked ribeye", "minecraft:cooked_rabbit", "&6Cooked ribeye", "Food", null, 64, NoEnchantments),
        new("Cookie", "minecraft:cookie", "&fCookie", "Food", 1, 64, NoEnchantments),
        new("Magical Apple", "minecraft:golden_apple", "&dMagical Apple", "Food", 5, 64, NoEnchantments),
        new("Apple", "minecraft:apple", "&9Apple", "Food", 3, 64, NoEnchantments),
        new("Steel Axe", "minecraft:iron_axe", "&9Steel Axe", "Weapons", 3, 1, NoEnchantments),
        new("Alloy Helmet", "minecraft:golden_helmet", "&fAlloy Helmet", "Armor", 1, 1, NoEnchantments),
        new("Oak Wood", "minecraft:oak_log", "&fOak Wood", "Resources", 1, 64, NoEnchantments),
        new("Alloy Leggings", "minecraft:golden_leggings", "&fAlloy Leggings", "Armor", 1, 1, NoEnchantments),
        new("Poison Pickaxe", "minecraft:diamond_pickaxe", "&5Poison Pickaxe", "Tools", null, 1, new (string, int)[] { ("minecraft:sharpness", 5), ("poison", 2) }),
        new("Coal", "minecraft:coal", "&fCoal", "Resources", 1, 64, NoEnchantments),
        new("Steak", "minecraft:cooked_beef", "&9Steak", "Food", 3, 64, NoEnchantments),
        new("Cobblestone", "minecraft:cobblestone", "&fCobblestone", "Resources", 1, 64, NoEnchantments),
        new("Cooked Chicken", "minecraft:cooked_chicken", "&bCooked Chicken", "Food", 4, 64, NoEnchantments),
        new("Raw Rabbit", "minecraft:rabbit", "&fRaw Rabbit", "Food", 1, 64, NoEnchantments),
        new("Raw Chicken", "minecraft:chicken", "&fRaw Chicken", "Food", 1, 64, NoEnchantments),
        new("Leather Helmet", "minecraft:leather_helmet", "&fLeather Helmet", "Armor", 1, 1, NoEnchantments),
        new("Leather Chestplate", "minecraft:leather_chestplate", "&fLeather Chestplate", "Armor", 1, 1, NoEnchantments),
        new("Bread", "minecraft:bread", "&9Bread", "Food", 3, 64, NoEnchantments),
        new("Leather Boots", "minecraft:leather_boots", "&fLeather Boots", "Armor", 1, 1, NoEnchantments),
        new("Leather Leggings", "minecraft:leather_leggings", "&fLeather Leggings", "Armor", 1, 1, NoEnchantments),
        new("Alloy Chestplate", "minecraft:golden_chestplate", "&fAlloy Chestplate", "Armor", 1, 1, NoEnchantments),
        new("Diamond Sword", "minecraft:diamond_sword", "&bDiamond Sword", "Weapons", 4, 1, NoEnchantments),
        new("Baked Potato", "minecraft:baked_potato", "&9Baked Potato", "Food", 3, 64, NoEnchantments),
        new("Life amulet", "minecraft:diamond", "&5Life amulet", "Trinkets", 4, 64, NoEnchantments),
        new("Diamond", "minecraft:diamond", "&bDiamond", "Resources", 4, 64, NoEnchantments),
        new("Mushroom stew", "minecraft:mushroom_stew", "&dMushroom stew", "Food", 5, 1, NoEnchantments),
        new("Pumpkin Pie", "minecraft:pumpkin_pie", "&fPumpkin Pie", "Food", 2, 64, NoEnchantments),
        new("Melon", "minecraft:melon_slice", "&9Melon", "Food", 3, 64, NoEnchantments),
        new("Potato", "minecraft:potato", "&fPotato", "Food", 1, 64, NoEnchantments),
        new("Firestone Sword", "minecraft:stone_sword", "&9Firestone Sword", "Weapons", 2, 1, NoEnchantments),
        new("Steel Boots", "minecraft:iron_boots", "&9Steel Boots", "Armor", 3, 1, NoEnchantments),
        new("Steel Leggings", "minecraft:iron_leggings", "&9Steel Leggings", "Armor", 3, 1, NoEnchantments),
        new("Steel Chestplate", "minecraft:iron_chestplate", "&9Steel Chestplate", "Armor", 3, 1, NoEnchantments),
        new("Steel Helmet", "minecraft:iron_helmet", "&9Steel Helmet", "Armor", 3, 1, NoEnchantments),
        new("Carrot", "minecraft:carrot", "&bCarrot", "Food", 4, 64, NoEnchantments),
        new("Raw Beef", "minecraft:beef", "&fRaw Beef", "Food", 1, 64, NoEnchantments),
        new("Raw Porkchop", "minecraft:porkchop", "&fRaw Porkchop", "Food", 1, 64, NoEnchantments),
        new("Alloy Boots", "minecraft:golden_boots", "&fAlloy Boots", "Armor", 1, 1, NoEnchantments),
        new("Cooked Porkchop", "minecraft:cooked_porkchop", "&fCooked Porkchop", "Food", 2, 64, NoEnchantments),
        new("Cooked Mutton", "minecraft:cooked_mutton", "&9Cooked Mutton", "Food", 3, 64, NoEnchantments),
        new("Cooked Salmon", "minecraft:cooked_cod", "&bCooked Salmon", "Food", 4, 64, NoEnchantments),
        new("Rabbit Stew", "minecraft:rabbit_stew", "&fRabbit Stew", "Food", 2, 1, NoEnchantments),
        new("Bladed Steel Sword", "minecraft:iron_sword", "&bBladed Steel Sword", "Weapons", 4, 1, NoEnchantments),
        new("Longbow", "minecraft:bow", "&6Longbow", "Weapons", 2, 1, NoEnchantments),
        new("Arrow", "minecraft:arrow", "&fArrow", "Weapons", 1, 64, NoEnchantments),
        new("Bladed Steel Boots", "minecraft:iron_boots", "&bBladed Steel Boots", "Armor", 4, 1, NoEnchantments),
        new("Chainmail Leggings", "minecraft:chainmail_leggings", "&bChainmail Leggings", "Armor", 4, 1, NoEnchantments),
        new("Chainmail Helmet", "minecraft:chainmail_helmet", "&bChainmail Helmet", "Armor", 4, 1, NoEnchantments),
        new("Lavonian Bow", "minecraft:bow", "&aLavonian Bow", "Weapons", 5, 1, new (string, int)[] { ("minecraft:infinity", 1), ("minecraft:power", 6), ("minecraft:unbreaking", 6) }),
        new("Diamond Boots", "minecraft:diamond_boots", "&bDiamond Boots", "Armor", 4, 1, new (string, int)[] { ("minecraft:protection", 1) }),
        new("Diamond Leggings", "minecraft:diamond_leggings", "&bDiamond Leggings", "Armor", 4, 1, new (string, int)[] { ("minecraft:protection", 1) }),
        new("Diamond Helmet", "minecraft:diamond_helmet", "&bDiamond Helmet", "Armor", 4, 1, new (string, int)[] { ("minecraft:protection", 1) }),
        new("Leather Pants", "minecraft:leather_leggings", "&fLeather Pants", "Armor", 1, 1, NoEnchantments),
        new("Golemheart Boots", "minecraft:diamond_boots", "&aGolemheart Boots", "Armor", 5, 1, new (string, int)[] { ("minecraft:protection", 6) }),
        new("Golemheart Chestplate", "minecraft:diamond_chestplate", "&aGolemheart Chestplate", "Armor", 5, 1, NoEnchantments),
        new("Halloween Armor Boots", "minecraft:iron_boots", "&5Halloween armor", "Armor", null, 1, new (string, int)[] { ("minecraft:protection", 3) }),
        new("Halloween Armor Leggings", "minecraft:iron_leggings", "&5Halloween armor", "Armor", null, 1, new (string, int)[] { ("minecraft:protection", 3) }),
        new("Enchanted Cake", "minecraft:cake", "&5Enchanted Cake", "Food", 5, 1, NoEnchantments),
        new("Standard Bow", "minecraft:bow", "&9Standard Bow", "Weapons", 3, 1, NoEnchantments),
        new("Skull splitter", "minecraft:iron_sword", "&9Skull splitter", "Weapons", 5, 1, new (string, int)[] { ("minecraft:sharpness", 4), ("health_boost", 1) }),
        new("Bladed Steel Leggings", "minecraft:iron_leggings", "&bBladed Steel Leggings", "Armor", 4, 1, NoEnchantments),
        new("Bladed Steel Chestplate", "minecraft:iron_chestplate", "&bBladed Steel Chestplate", "Armor", 4, 1, NoEnchantments),
        new("Bladed Steel Helmet", "minecraft:iron_helmet", "&bBladed Steel Helmet", "Armor", 4, 1, NoEnchantments),
        new("Golemheart Leggings", "minecraft:diamond_leggings", "&aGolemheart Leggings", "Armor", 5, 1, NoEnchantments),
        new("Practice Sword", "minecraft:wooden_sword", "&fPractice Sword", "Weapons", 1, 1, NoEnchantments),
        new("Wither Pickaxe", "minecraft:diamond_pickaxe", "&0Wither Pickaxe", "Tools", null, 1, new (string, int)[] { ("minecraft:sharpness", 5), ("wither", 2) }),
        new("Pickaxe of Good Health", "minecraft:diamond_pickaxe", "&aPickaxe of Good Health", "Tools", null, 1, new (string, int)[] { ("minecraft:sharpness", 5), ("armor_repair", 1), ("health_boost", 1) }),
        new("Blindness Pickaxe", "minecraft:diamond_pickaxe", "&8Blindness Pickaxe", "Tools", null, 1, new (string, int)[] { ("minecraft:sharpness", 5), ("blindness", 2) }),
        new("Donator pickaxe", "minecraft:diamond_pickaxe", "&2Donator pickaxe", "Tools", null, 1, new (string, int)[] { ("minecraft:efficiency", 2), ("minecraft:unbreaking", 2) }),
        new("Cooked Rabbit", "minecraft:cooked_rabbit", "&9Cooked Rabbit", "Food", 3, 64, NoEnchantments),
        new("Golemheart Helmet", "minecraft:diamond_helmet", "&aGolemheart Helmet", "Armor", 5, 1, new (string, int)[] { ("minecraft:aqua_affinity", 1), ("minecraft:protection", 6), ("minecraft:respiration", 3), ("minecraft:unbreaking", 6), ("health_boost", 1) }),
        new("Diamond Pickaxe", "minecraft:diamond_pickaxe", "&bDiamond Pickaxe", "Tools", 4, 1, NoEnchantments),
        new("Diamond Chestplate", "minecraft:diamond_chestplate", "&bDiamond Chestplate", "Armor", 4, 1, new (string, int)[] { ("minecraft:protection", 1) }),
        new("Practice Bow", "minecraft:bow", "&fPractice Bow", "Weapons", 1, 1, NoEnchantments),
    };

    public static async Task SeedCanonicalAsync(
        KnKDbContext context,
        IMinecraftMaterialCatalogService? materialCatalog = null,
        IMinecraftEnchantmentCatalogService? enchantmentCatalog = null,
        ILogger? logger = null,
        CancellationToken cancellationToken = default)
    {
        var created = new Dictionary<string, int>();
        void Count(string what) => created[what] = created.GetValueOrDefault(what) + 1;

        // --- MinecraftMaterialRef (icons) ---
        var iconKeys = Categories.Select(c => c.IconKey)
            .Concat(Blueprints.Select(b => b.IconKey))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
        var materials = ByKey(
            await context.MinecraftMaterialRefs.Where(m => iconKeys.Contains(m.NamespaceKey)).ToListAsync(cancellationToken),
            m => m.NamespaceKey, m => m.Id);
        var materialCatalogByKey = materialCatalog?.GetAll()
            .GroupBy(e => e.NamespaceKey, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase)
            ?? new Dictionary<string, MinecraftMaterialCatalogEntry>(StringComparer.OrdinalIgnoreCase);
        foreach (var key in iconKeys)
        {
            if (materials.ContainsKey(key)) continue;
            materialCatalogByKey.TryGetValue(key, out var entry);
            var material = new MinecraftMaterialRef
            {
                NamespaceKey = key,
                Category = entry?.Category ?? FallbackMaterialCategory,
                LegacyName = entry?.LegacyName,
                IconUrl = entry?.IconUrl,
            };
            context.MinecraftMaterialRefs.Add(material);
            materials[key] = material;
            Count(nameof(MinecraftMaterialRef));
        }

        // --- Tag ---
        var tags = ByKey(await context.Tags.ToListAsync(cancellationToken), t => t.Name, t => t.Id);
        if (!tags.TryGetValue(LegacyTag, out var legacyTag))
        {
            legacyTag = new Tag { Name = LegacyTag };
            context.Tags.Add(legacyTag);
            Count(nameof(Tag));
        }

        // --- Category ---
        var categories = ByKey(await context.Categories.ToListAsync(cancellationToken), c => c.Name, c => c.Id);
        foreach (var (name, iconKey) in Categories)
        {
            if (categories.ContainsKey(name)) continue;
            var category = new Category { Name = name, IconMaterialRef = materials[iconKey] };
            context.Categories.Add(category);
            categories[name] = category;
            Count(nameof(Category));
        }

        // --- Grade (by star count: that's what v1 stored) ---
        var grades = (await context.Grades.ToListAsync(cancellationToken))
            .GroupBy(g => g.Stars)
            .ToDictionary(g => g.Key, g => g.OrderBy(x => x.Id).First());
        foreach (var (name, stars) in Grades)
        {
            if (grades.ContainsKey(stars)) continue;
            var grade = new Grade { Name = name, Stars = stars };
            context.Grades.Add(grade);
            grades[stars] = grade;
            Count(nameof(Grade));
        }

        // --- EnchantmentDefinition (+ MinecraftEnchantmentRef for new vanilla ones) ---
        var enchantments = ByKey(await context.EnchantmentDefinitions.ToListAsync(cancellationToken), e => NormalizeEnchantmentKey(e.Key), e => e.Id);
        var enchantmentRefs = ByKey(await context.MinecraftEnchantmentRefs.ToListAsync(cancellationToken), r => r.NamespaceKey, r => r.Id);
        var missingCustom = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var key in Blueprints.SelectMany(b => b.Enchantments).Select(e => e.Key).Distinct(StringComparer.OrdinalIgnoreCase))
        {
            if (enchantments.ContainsKey(NormalizeEnchantmentKey(key))) continue;
            if (!key.StartsWith("minecraft:", StringComparison.OrdinalIgnoreCase))
            {
                missingCustom.Add(key);
                continue;
            }

            var catalogEntry = enchantmentCatalog?.GetByNamespaceKey(key);
            if (!enchantmentRefs.TryGetValue(key, out var enchantmentRef))
            {
                enchantmentRef = new MinecraftEnchantmentRef
                {
                    NamespaceKey = key,
                    LegacyName = catalogEntry?.LegacyName,
                    Category = catalogEntry?.Category,
                    IconUrl = catalogEntry?.IconUrl,
                    MaxLevel = catalogEntry?.MaxLevel ?? 1,
                    DisplayName = catalogEntry?.DisplayName ?? ToDisplayName(key),
                    IsCustom = false,
                };
                context.MinecraftEnchantmentRefs.Add(enchantmentRef);
                enchantmentRefs[key] = enchantmentRef;
                Count(nameof(MinecraftEnchantmentRef));
            }

            var definition = new EnchantmentDefinition
            {
                Key = key,
                DisplayName = catalogEntry?.DisplayName ?? ToDisplayName(key),
                Description = string.Empty,
                IsCustom = false,
                MaxLevel = catalogEntry?.MaxLevel ?? 1,
                BaseEnchantmentRef = enchantmentRef,
            };
            context.EnchantmentDefinitions.Add(definition);
            enchantments[NormalizeEnchantmentKey(key)] = definition;
            Count(nameof(EnchantmentDefinition));
        }

        if (missingCustom.Count > 0)
        {
            logger?.LogWarning(
                "ItemBlueprintV1Seed: custom enchantment definitions not found (seeded by AbilityDefinition.SeedCanonicalAsync); skipping them on new blueprints: {Keys}",
                string.Join(", ", missingCustom));
        }

        // --- ItemBlueprint (+ default enchantments and legacy tag for newly created blueprints only) ---
        // Prices, origins and descriptions are deliberately left unset: v1 playerdata doesn't carry them.
        var blueprints = ByKey(await context.ItemBlueprints.ToListAsync(cancellationToken), b => b.Name, b => b.Id);
        var reused = new List<string>();
        foreach (var spec in Blueprints)
        {
            if (blueprints.ContainsKey(spec.Name))
            {
                reused.Add(spec.Name);
                continue;
            }

            var blueprint = new ItemBlueprint
            {
                Name = spec.Name,
                DefaultDisplayName = spec.DisplayName,
                IconMaterial = materials[spec.IconKey],
                Category = categories[spec.Category],
                Grade = spec.Stars is int stars ? grades[stars] : null,
                DefaultQuantity = 1,
                MaxStackSize = spec.MaxStackSize,
            };
            blueprint.Tags.Add(new ItemBlueprintTag { ItemBlueprint = blueprint, Tag = legacyTag });
            Count(nameof(ItemBlueprintTag));
            foreach (var (key, level) in spec.Enchantments)
            {
                if (!enchantments.TryGetValue(NormalizeEnchantmentKey(key), out var definition)) continue;
                blueprint.DefaultEnchantments.Add(new ItemBlueprintDefaultEnchantment
                {
                    ItemBlueprint = blueprint,
                    EnchantmentDefinition = definition,
                    Level = level,
                });
                Count(nameof(ItemBlueprintDefaultEnchantment));
            }
            context.ItemBlueprints.Add(blueprint);
            blueprints[spec.Name] = blueprint;
            Count(nameof(ItemBlueprint));
        }

        if (created.Count > 0)
        {
            await context.SaveChangesAsync(cancellationToken);
        }

        logger?.LogInformation(
            "ItemBlueprintV1Seed complete. Created: {Created}. Existing blueprints left as-is: {Reused}",
            created.Count == 0 ? "nothing" : string.Join(", ", created.Select(kv => $"{kv.Value} {kv.Key}")),
            reused.Count == 0 ? "none" : string.Join(", ", reused));
    }

    // Vanilla keys match as-is ("minecraft:sharpness"); custom keys match the way the plugin's
    // EnchantmentDefinitionBukkitMapper resolves them ("blindness", "knk:blindness" and
    // "Blindness" are the same enchantment).
    private static string NormalizeEnchantmentKey(string key)
    {
        var trimmed = key.Trim().ToLowerInvariant();
        if (trimmed.StartsWith("minecraft:", StringComparison.Ordinal)) return trimmed;
        var colon = trimmed.IndexOf(':');
        if (colon >= 0) trimmed = trimmed[(colon + 1)..];
        return trimmed.Replace('-', '_').Replace(' ', '_');
    }

    private static string ToDisplayName(string namespaceKey)
    {
        var key = namespaceKey[(namespaceKey.IndexOf(':') + 1)..];
        return string.Join(' ', key.Split('_', StringSplitOptions.RemoveEmptyEntries)
            .Select(w => char.ToUpperInvariant(w[0]) + w[1..]));
    }

    // Natural-key lookup: case-insensitive, and if an admin has somehow created two rows with the
    // same key (none of these columns has a unique index), the oldest one wins.
    private static Dictionary<string, T> ByKey<T>(IEnumerable<T> rows, Func<T, string?> key, Func<T, int> id) =>
        rows.Where(r => !string.IsNullOrWhiteSpace(key(r)))
            .GroupBy(r => key(r)!.Trim(), StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.OrderBy(id).First(), StringComparer.OrdinalIgnoreCase);
}
